  - name: Download holland_mysqldump.py 
    get_url: 
      url: https://raw.githubusercontent.com/racker/rackspace-monitoring-agent-plugins-contrib/master/holland_mysqldump.py 
      dest: /usr/lib/rackspace-monitoring-agent/plugins/holland_mysqldump.py
      mode: 0744
      owner: root
      group: root
    notify: restart rackspace-monitoring-agent

  - name: Copy holland_mysqldump.yaml 
    copy: src=holland_mysqldump.yaml dest=/etc/rackspace-monitoring-agent.conf.d/
    notify: restart rackspace-monitoring-agent
